-- delaware Manufacturing Playbook — Supabase Seed Script
-- Creates 4 tables and inserts all content data (7 storylines × 3 personas = 21 content blocks)
-- Run this in the Supabase SQL Editor to set up the database

-- ═══════════════════════════════════════════════════════
-- 1. DROP EXISTING TABLES (if re-seeding)
-- ═══════════════════════════════════════════════════════
DROP TABLE IF EXISTS storyline_content CASCADE;
DROP TABLE IF EXISTS storylines CASCADE;
DROP TABLE IF EXISTS sub_segments CASCADE;
DROP TABLE IF EXISTS personas CASCADE;

-- ═══════════════════════════════════════════════════════
-- 2. CREATE TABLES
-- ═══════════════════════════════════════════════════════

CREATE TABLE personas (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  emoji TEXT NOT NULL,
  focus TEXT NOT NULL,
  care_most JSONB NOT NULL DEFAULT '[]',
  keeps_up_at_night JSONB NOT NULL DEFAULT '[]'
);

CREATE TABLE sub_segments (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  short TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE storylines (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  accent TEXT NOT NULL,
  relevant_segments JSONB NOT NULL DEFAULT '[]',
  sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE storyline_content (
  id SERIAL PRIMARY KEY,
  storyline_id TEXT NOT NULL REFERENCES storylines(id),
  persona_id TEXT NOT NULL REFERENCES personas(id),
  pain_point JSONB NOT NULL,
  strategic_talking_points JSONB NOT NULL DEFAULT '[]',
  tactical_solutions JSONB NOT NULL DEFAULT '[]',
  market_insights JSONB NOT NULL DEFAULT '[]',
  reference_customers JSONB NOT NULL DEFAULT '[]',
  conversation_starters JSONB NOT NULL DEFAULT '[]',
  UNIQUE(storyline_id, persona_id)
);

-- ═══════════════════════════════════════════════════════
-- 3. DISABLE RLS (internal tool, no auth for V1)
-- ═══════════════════════════════════════════════════════
ALTER TABLE personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE sub_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE storylines ENABLE ROW LEVEL SECURITY;
ALTER TABLE storyline_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on personas" ON personas FOR SELECT USING (true);
CREATE POLICY "Allow public read on sub_segments" ON sub_segments FOR SELECT USING (true);
CREATE POLICY "Allow public read on storylines" ON storylines FOR SELECT USING (true);
CREATE POLICY "Allow public read on storyline_content" ON storyline_content FOR SELECT USING (true);

-- ═══════════════════════════════════════════════════════
-- 4. INSERT PERSONAS
-- ═══════════════════════════════════════════════════════

INSERT INTO personas (id, label, subtitle, emoji, focus, care_most, keeps_up_at_night) VALUES
('c-level', 'C-Level', 'CEO / CFO', '👔', 'Strategic growth, ROI, competitive positioning, risk',
  '["Revenue growth and margin protection in volatile markets","Return on digital investments — measurable, not theoretical","Competitive differentiation through technology and innovation","Risk management across supply chain, cyber, and compliance","Sustainability commitments and ESG reporting obligations","Talent retention and workforce transformation"]',
  '["Are we investing in the right technology or burning cash on hype?","Can our supply chain survive the next disruption?","Are we losing market share to digitally-native competitors?","Will we meet tightening regulatory and sustainability deadlines?","Do we have the talent pipeline to execute our strategy?"]'
),
('it-decision-maker', 'IT Decision Maker', 'CIO / CTO', '💻', 'Architecture, integration, cloud, security, roadmap',
  '["Modernising legacy architecture without disrupting operations","Cloud strategy: when to migrate, what to keep on-premise","Integration across ERP, MES, PLM, IoT, and data platforms","Cybersecurity posture in an increasingly connected factory","Building a composable, API-first technology landscape","Balancing innovation velocity with governance and compliance"]',
  '["Technical debt is slowing down every project we start","Shadow IT is creating data silos and security blind spots","We can''t find or retain engineers who know our stack","Our ERP roadmap is unclear — on-prem vs. cloud, SAP vs. Microsoft","A ransomware attack could shut down production for weeks"]'
),
('operations-leader', 'Operations Leader', 'COO / VP Ops', '🏭', 'Shopfloor efficiency, workforce, supply chain, quality, energy',
  '["OEE and throughput improvement across production lines","Supply chain visibility and supplier risk mitigation","Quality management and first-pass yield improvement","Workforce productivity despite labor shortages","Energy consumption reduction and sustainability targets","Predictive maintenance to reduce unplanned downtime"]',
  '["Unplanned downtime is costing us millions annually","We''re drowning in data but can''t turn it into action","Skilled operators are retiring and knowledge walks out the door","Supply disruptions force constant firefighting and replanning","Quality escapes are increasing as complexity grows"]'
);

-- ═══════════════════════════════════════════════════════
-- 5. INSERT SUB-SEGMENTS
-- ═══════════════════════════════════════════════════════

INSERT INTO sub_segments (id, label, short, description) VALUES
('industrial-equipment', 'Industrial Equipment & Machinery', 'Industrial Equipment', 'OEMs producing capital goods — ETO/CTO with complex BOMs and field service'),
('components', 'Manufacturing Components', 'Components', 'Electronics, precision parts, connectors — high-mix/low-volume, tight quality'),
('infrastructure', 'Infrastructure & Appliances', 'Infrastructure', 'Building products, HVAC, lighting — MTS/MTO with variant complexity'),
('aerospace', 'Aerospace & Defense', 'Aerospace', 'Highly regulated, long lifecycles, multi-domain engineering'),
('medical', 'Medical Equipment', 'Medical', 'Medical devices, diagnostics — strict regulation, full traceability'),
('automotive', 'Automotive', 'Automotive', 'OEMs and tier suppliers — electrification, AUTOSAR, supply chain restructuring');

-- ═══════════════════════════════════════════════════════
-- 6. INSERT STORYLINES
-- ═══════════════════════════════════════════════════════

INSERT INTO storylines (id, name, icon, accent, relevant_segments, sort_order) VALUES
('factory-of-the-future', 'Factory of the Future', '🏗️', '#6366f1', '["industrial-equipment","automotive","aerospace","components"]', 1),
('erp-evolves', 'ERP that Evolves with Your Business', '⚙️', '#f59e0b', '["industrial-equipment","infrastructure","components","automotive"]', 2),
('value-of-data', 'Value of Data', '📊', '#10b981', '["industrial-equipment","automotive","components","aerospace","medical"]', 3),
('digital-business', 'Driving Digital Business', '🚀', '#8b5cf6', '["industrial-equipment","infrastructure","components"]', 4),
('frontline-workers', 'Unburden Frontline Workers', '👷', '#ec4899', '["industrial-equipment","aerospace","medical","automotive","components"]', 5),
('resilience-compliance', 'Resilience, Compliance & Control', '🛡️', '#ef4444', '["aerospace","medical","automotive","industrial-equipment","components","infrastructure"]', 6),
('talent-knowledge', 'Unlocking Talent, Leveraging Knowledge', '🧠', '#0ea5e9', '["aerospace","medical","industrial-equipment","automotive"]', 7);

-- ═══════════════════════════════════════════════════════
-- 7. INSERT STORYLINE CONTENT (21 rows)
-- ═══════════════════════════════════════════════════════

-- ─── Factory of the Future × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('factory-of-the-future', 'c-level',
  '{"headline":"Your factory runs on gut feel, not data","description":"Most discrete manufacturers still rely on manual reporting, disconnected systems, and tribal knowledge to make production decisions. This leads to reactive operations, missed optimization opportunities, and an inability to scale efficiently.","dataPoint":"Only 26% of manufacturers have successfully scaled Industry 4.0 initiatives beyond pilot stage — McKinsey 2024"}',
  '[{"headline":"Digital twins unlock predictive economics","detail":"A digital twin of your production environment lets you simulate changes before committing capital — test line reconfigurations, predict bottlenecks, and optimize throughput without halting production."},{"headline":"Smart factories deliver margin, not just efficiency","detail":"The business case isn''t just ''fewer operators'' — it''s faster time-to-market, lower scrap rates, real-time quality assurance, and the ability to profitably handle higher product mix."},{"headline":"First-mover advantage is narrowing","detail":"Competitors are moving from pilots to scale. The window to leapfrog with Industry 4.0 is closing — the cost of inaction compounds every quarter."}]',
  '[{"name":"Azure IoT + Digital Twins","description":"Cloud-connected shopfloor with real-time digital twin modeling for predictive operations.","partner":"Microsoft"},{"name":"SAP Digital Manufacturing","description":"Integrated MES-to-ERP execution with AI-powered production scheduling and quality.","partner":"SAP"},{"name":"Sight Machine / Databricks","description":"Manufacturing data lake with AI/ML models for yield optimization and anomaly detection.","partner":"Sight Machine"},{"name":"PTC ThingWorx + Kepware","description":"Industrial IoT platform connecting legacy equipment to modern analytics.","partner":"PTC"}]',
  '[{"stat":"Smart factory initiatives can boost productivity by up to 30% and reduce quality costs by 35%","source":"Deloitte & MAPI Smart Factory Study, 2024"},{"stat":"The global digital twin market in manufacturing will reach $14.7B by 2028, growing at 35% CAGR","source":"MarketsandMarkets, 2024"},{"stat":"73% of manufacturing CEOs plan to increase digital factory investments despite economic headwinds","source":"PwC Global CEO Survey, 2024"}]',
  '["Atlas Copco","Picanol","Vandewiele","Daikin Europe","CNH Industrial"]',
  '["What percentage of your production decisions are currently based on real-time data versus historical reports?","Have you calculated the cost of unplanned downtime across your plants in the last 12 months?","If you could simulate production changes before implementing them, what would you test first?"]'
);

-- ─── Factory of the Future × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('factory-of-the-future', 'it-decision-maker',
  '{"headline":"Your OT and IT worlds speak different languages","description":"Connecting shopfloor equipment (PLCs, SCADA, sensors) to enterprise systems (ERP, MES, analytics) requires bridging decades of protocol differences, security gaps, and organizational silos. Most IT teams lack OT expertise, and most OT teams distrust IT-led projects.","dataPoint":"68% of manufacturers cite IT/OT convergence as their #1 technical challenge in digital transformation — Gartner 2024"}',
  '[{"headline":"Unified architecture, not point solutions","detail":"The answer isn''t 50 different IoT platforms — it''s a reference architecture that standardizes how data flows from PLC to cloud, with clear integration patterns and security boundaries."},{"headline":"Edge computing reduces cloud dependency","detail":"Not everything belongs in the cloud. Edge processing at the machine level enables sub-second response times for critical control loops while still feeding aggregated data upstream for analytics."},{"headline":"Standards-based connectivity future-proofs your investment","detail":"OPC UA, MQTT, and ISA-95 aren''t buzzwords — they''re the foundation for connecting any equipment to any platform without vendor lock-in."}]',
  '[{"name":"Azure IoT Edge + Arc","description":"Hybrid edge-cloud architecture for real-time processing with central management.","partner":"Microsoft"},{"name":"PTC Kepware + ThingWorx","description":"Universal industrial connectivity with 150+ device drivers and rapid application development.","partner":"PTC"},{"name":"SAP Integration Suite","description":"Enterprise integration platform connecting ERP, MES, and IoT with pre-built manufacturing connectors.","partner":"SAP"},{"name":"Unified Namespace (UNS)","description":"Event-driven data architecture using MQTT brokers as the single source of truth for all factory data.","partner":"HiveMQ / Eclipse"}]',
  '[{"stat":"By 2026, 75% of new OT systems will be designed to integrate with IT systems by default","source":"Gartner, 2024"},{"stat":"Edge computing in manufacturing will grow to $17.1B by 2028 as latency-critical use cases expand","source":"IDC, 2024"},{"stat":"Manufacturers with mature IT/OT integration achieve 22% higher OEE than those with siloed architectures","source":"LNS Research, 2024"}]',
  '["Barco","Bekaert","Niko","Etex Group","Melexis"]',
  '["How many different protocols and connectivity solutions are currently running across your shopfloor?","What''s your current architecture for getting machine data into your analytics or ERP platform?","Have you established clear ownership boundaries between your IT and OT teams for connected factory initiatives?"]'
);

-- ─── Factory of the Future × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('factory-of-the-future', 'operations-leader',
  '{"headline":"You''re flying blind between planned and actual production","description":"The gap between what ERP says should happen and what actually happens on the shopfloor is where margin leaks. Without real-time visibility into machine status, operator performance, and material flow, you''re always reacting instead of optimizing.","dataPoint":"Manufacturers lose an average of 800 hours of production time per year due to unplanned downtime — Aberdeen Group, 2024"}',
  '[{"headline":"Real-time OEE changes behavior","detail":"When operators and supervisors see live OEE dashboards at the line, they self-correct. Visibility alone can improve OEE by 5-10% before any automation investment."},{"headline":"Predictive maintenance prevents firefighting","detail":"Moving from time-based to condition-based maintenance reduces unplanned stops by 30-50% and extends equipment life. The ROI is measured in months, not years."},{"headline":"Digital twins for continuous improvement","detail":"Simulate line changes, shift patterns, and product mix scenarios without risking production. Data-driven kaizen beats gut-feel kaizen every time."}]',
  '[{"name":"SAP Digital Manufacturing Cloud","description":"Integrated MES with real-time OEE, operator dashboards, and AI-assisted scheduling.","partner":"SAP"},{"name":"Azure IoT + Power BI Shopfloor","description":"Real-time machine monitoring dashboards with alerts and trend analysis accessible on any device.","partner":"Microsoft"},{"name":"PTC ThingWorx + Vuforia","description":"IoT monitoring combined with AR-guided maintenance procedures for faster MTTR.","partner":"PTC"},{"name":"Predictive Maintenance as a Service","description":"delaware''s managed service combining sensor data, ML models, and maintenance workflow integration.","partner":"delaware"}]',
  '[{"stat":"Predictive maintenance can reduce maintenance costs by 25-30% and eliminate 70-75% of breakdowns","source":"Deloitte Analytics Institute, 2024"},{"stat":"Real-time production monitoring delivers average OEE improvement of 11% in the first year","source":"LNS Research, 2024"},{"stat":"Only 18% of manufacturers have full real-time visibility across all production assets","source":"Gartner Manufacturing Survey, 2024"}]',
  '["Vandewiele","Picanol","Atlas Copco","Daikin Europe","Ontex"]',
  '["How do you currently track OEE — is it real-time, shift-end, or weekly?","What''s your current ratio of planned vs. unplanned maintenance activities?","If a machine goes down right now, how long before the right person knows and can respond?"]'
);

-- ─── ERP Evolves × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('erp-evolves', 'c-level',
  '{"headline":"Your ERP is a constraint, not an enabler","description":"Legacy ERP systems built for yesterday''s business model are holding back growth. Acquisitions create multi-ERP landscapes, customizations make upgrades impossible, and the total cost of ownership keeps rising while agility keeps falling.","dataPoint":"43% of manufacturers say their current ERP is a barrier to growth and innovation — IDC Manufacturing Insights, 2024"}',
  '[{"headline":"Cloud ERP isn''t just a migration — it''s a business reset","detail":"Moving to S/4HANA or D365 is an opportunity to standardize processes, eliminate customization debt, and build a composable foundation that adapts to new business models."},{"headline":"Two-speed ERP for M&A agility","detail":"A clean core ERP with a composable integration layer lets you onboard acquisitions in weeks instead of months — connect first, harmonize later."},{"headline":"Total cost of ownership drops by 30-40%","detail":"Cloud ERP eliminates infrastructure cost, reduces upgrade pain, and shifts from CapEx to OpEx — freeing capital for value-creating investments."}]',
  '[{"name":"SAP S/4HANA Cloud","description":"Next-gen ERP with embedded analytics, AI, and industry-specific manufacturing processes.","partner":"SAP"},{"name":"Microsoft Dynamics 365","description":"Modular cloud ERP with strong integration to Microsoft 365, Power Platform, and Azure.","partner":"Microsoft"},{"name":"SAP RISE","description":"SAP''s managed cloud offering that bundles infrastructure, tools, and services for faster S/4 migration.","partner":"SAP"},{"name":"delaware SPEED methodology","description":"Accelerated ERP implementation framework with pre-configured industry templates for discrete manufacturing.","partner":"delaware"}]',
  '[{"stat":"By 2027, 70% of new ERP deployments will be cloud-based, up from 30% in 2023","source":"Gartner, 2024"},{"stat":"Manufacturers moving to cloud ERP report 23% faster financial close and 34% better inventory accuracy","source":"SAP Customer Success, 2024"},{"stat":"The average age of ERP systems in discrete manufacturing is 11.7 years — well past the innovation curve","source":"Panorama Consulting, 2024"}]',
  '["Niko","Reynaers Aluminium","Etex Group","TVH","Haco"]',
  '["When was the last time your ERP was a competitive advantage rather than a constraint?","How many ERP systems are running across your organization today — and what does that fragmentation cost you?","If you could redesign your core processes from scratch today, what would you change first?"]'
);

-- ─── ERP Evolves × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('erp-evolves', 'it-decision-maker',
  '{"headline":"Customizations have turned your ERP into a black box","description":"Years of modifications, bolt-ons, and workarounds have created an ERP that no one fully understands, no one dares upgrade, and everyone complains about. Every change request takes months and costs a fortune.","dataPoint":"On average, discrete manufacturers run 3.2 ERP systems with over 200 custom modifications each — Rimini Street, 2024"}',
  '[{"headline":"Clean core is the strategy — extensions are the tactic","detail":"Modern ERP platforms (S/4HANA, D365) support a clean core with side-by-side extensions. This means standard upgrades, faster innovation adoption, and customizations that don''t create technical debt."},{"headline":"Composable ERP is not optional","detail":"The future is a core ERP surrounded by best-of-breed applications connected via APIs and an integration platform. Planning for composability now avoids another decade of monolithic lock-in."},{"headline":"Migration is not lift-and-shift","detail":"A cloud ERP transformation is a chance to re-engineer data models, master data, and integrations. Treat it as an architecture modernization, not a server move."}]',
  '[{"name":"SAP BTP (Business Technology Platform)","description":"Extension platform for S/4HANA with low-code tools, integration services, and AI capabilities.","partner":"SAP"},{"name":"D365 + Power Platform","description":"Extend Dynamics 365 with Power Apps, Power Automate, and Copilot for rapid business process innovation.","partner":"Microsoft"},{"name":"delaware Integration Framework","description":"Pre-built integration patterns for connecting ERP to MES, PLM, WMS, and CRM in manufacturing.","partner":"delaware"},{"name":"Data Migration Factory","description":"delaware''s industrialized approach to ERP data migration with automated validation and cleansing.","partner":"delaware"}]',
  '[{"stat":"78% of ERP projects that fail do so because of poor data migration and inadequate change management","source":"Panorama Consulting, 2024"},{"stat":"Organizations using composable ERP architectures implement new capabilities 80% faster","source":"Gartner, 2024"},{"stat":"SAP will end maintenance for ECC by 2027 — forcing the hand for 30,000+ customers globally","source":"SAP, 2024"}]',
  '["Reynaers Aluminium","Haco","Niko","Bekaert","TVH"]',
  '["How many custom modifications are running on your current ERP — and how many are still actually needed?","What''s your current upgrade cycle, and how painful is each upgrade?","Have you assessed the impact of SAP ECC end-of-life on your technology roadmap?"]'
);

-- ─── ERP Evolves × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('erp-evolves', 'operations-leader',
  '{"headline":"Your ERP doesn''t reflect what actually happens on the shopfloor","description":"Production reality and ERP data are always out of sync. Bills of material are inaccurate, lead times are fictional, and planning runs on spreadsheets that supplement what ERP can''t do. The result: constant expediting, excess inventory, and missed deliveries.","dataPoint":"62% of production planners supplement their ERP with spreadsheets for daily scheduling — APICS, 2024"}',
  '[{"headline":"Integrated planning closes the execution gap","detail":"When MES feeds actual production data back into ERP planning in real-time, you get accurate lead times, realistic capacity plans, and the ability to promise delivery dates you can keep."},{"headline":"Variant configuration should be a strength, not a nightmare","detail":"Modern ERP handles engineer-to-order and configure-to-order natively. Complex BOMs, routing variants, and customer-specific configurations should flow seamlessly from quote to shopfloor."},{"headline":"Mobile ERP puts transactions where work happens","detail":"Goods receipts, time confirmations, and quality inspections should happen at the point of activity — not 4 hours later when someone gets to a desktop terminal."}]',
  '[{"name":"SAP PP/DS + IBP","description":"Advanced planning and scheduling with finite capacity planning and scenario simulation.","partner":"SAP"},{"name":"D365 Supply Chain Management","description":"Integrated production planning with demand sensing, inventory optimization, and vendor collaboration.","partner":"Microsoft"},{"name":"SAP Digital Manufacturing","description":"Bridge the gap between ERP planning and shopfloor execution with real-time production insights.","partner":"SAP"},{"name":"delaware Shopfloor Integration","description":"Pre-built connectors and mobile apps for real-time ERP transactions at the machine.","partner":"delaware"}]',
  '[{"stat":"Manufacturers with integrated ERP-MES achieve 17% better on-time delivery and 24% lower WIP inventory","source":"Aberdeen Group, 2024"},{"stat":"65% of discrete manufacturers still use spreadsheets as their primary planning tool alongside ERP","source":"APICS / ASCM, 2024"},{"stat":"Mobile ERP adoption on the shopfloor reduces data entry errors by 43% and saves 2.1 hours per operator per week","source":"SAP Customer Benchmark, 2024"}]',
  '["Picanol","Haco","Vandewiele","Ontex","Reynaers Aluminium"]',
  '["How accurate are your ERP lead times compared to actual production — within 10%, 25%, or more?","How much of your daily planning still happens outside the ERP system?","If you could fix one thing about your current ERP from an operations perspective, what would it be?"]'
);

-- ─── Value of Data × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('value-of-data', 'c-level',
  '{"headline":"You have more data than ever — and less insight than you need","description":"Manufacturing generates petabytes of data from machines, ERPs, quality systems, and supply chains. But without a data strategy, this data sits in silos, is inconsistent, and fails to drive the decisions that matter. You''re data-rich but insight-poor.","dataPoint":"Less than 25% of manufacturing data is analyzed — over 75% goes unused — IDC, 2024"}',
  '[{"headline":"Data is a balance sheet asset — treat it like one","detail":"Companies that manage data as a strategic asset achieve 2-3x better margins than peers. This means investing in governance, quality, and literacy — not just dashboards."},{"headline":"Manufacturing intelligence drives competitive moats","detail":"The manufacturers who win will be those who can predict quality issues before they occur, optimize pricing in real-time, and sense demand shifts weeks ahead of competitors."},{"headline":"AI is only as good as your data foundation","detail":"Before jumping to AI copilots and generative AI, you need clean, governed, integrated data. The unglamorous work of data strategy is the prerequisite for every AI use case."}]',
  '[{"name":"Microsoft Fabric","description":"Unified analytics platform combining data lake, data warehouse, and BI in a single SaaS offering.","partner":"Microsoft"},{"name":"SAP Datasphere","description":"Business data fabric connecting SAP and non-SAP data with built-in data governance and modeling.","partner":"SAP"},{"name":"Databricks Lakehouse","description":"Open data platform for manufacturing analytics, ML model training, and real-time streaming.","partner":"Databricks"},{"name":"delaware Data Strategy Workshop","description":"Structured approach to assess data maturity, define governance, and build a value-driven data roadmap.","partner":"delaware"}]',
  '[{"stat":"Data-driven manufacturers are 23x more likely to acquire customers and 6x more likely to retain them","source":"McKinsey Global Institute, 2024"},{"stat":"70% of manufacturing AI projects fail due to poor data quality, not algorithm problems","source":"Gartner, 2024"},{"stat":"Manufacturers who invest in data governance see 40% faster time-to-insight for new analytics use cases","source":"IDC, 2024"}]',
  '["Barco","Bekaert","Atlas Copco","Melexis","Etex Group"]',
  '["If your board asked ''what is our data worth?'' today — could you answer that question?","How many versions of the truth exist across your organization for key metrics like OEE, yield, or OTIF?","What''s preventing you from using AI in production today — is it technology, data, or trust?"]'
);

-- ─── Value of Data × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('value-of-data', 'it-decision-maker',
  '{"headline":"Your data landscape is a patchwork of silos and pipelines","description":"Every department has its own reporting, its own extracts, its own version of the truth. IT spends more time maintaining brittle ETL pipelines and answering ''why don''t these numbers match?'' than enabling new insights. Data quality is everyone''s problem and nobody''s job.","dataPoint":"Data engineers spend 40-60% of their time on data quality issues and pipeline maintenance — Fivetran/Census, 2024"}',
  '[{"headline":"A data platform strategy beats a tool strategy","detail":"Don''t pick tools first. Define your data mesh/fabric architecture, then select platforms that fit. The goal is a self-service data ecosystem with governance guardrails."},{"headline":"IT/OT data integration is the manufacturing differentiator","detail":"The real value isn''t in another BI dashboard — it''s in combining machine data (OT) with business data (IT) to enable use cases that neither domain can deliver alone."},{"headline":"Data governance is enablement, not restriction","detail":"Good governance makes data findable, trustworthy, and secure. It accelerates analytics projects instead of slowing them down. Frame it as ''data enablement'' to win business support."}]',
  '[{"name":"Microsoft Fabric + Purview","description":"Unified analytics with built-in data governance, cataloging, and lineage tracking.","partner":"Microsoft"},{"name":"SAP Datasphere + Analytics Cloud","description":"Federated data access across SAP landscapes with semantic modeling and planning.","partner":"SAP"},{"name":"Databricks Unity Catalog","description":"Open data governance for lakehouse architecture with fine-grained access control.","partner":"Databricks"},{"name":"delaware Data Platform Accelerator","description":"Pre-built manufacturing data models and pipelines for fast deployment on Azure or SAP.","partner":"delaware"}]',
  '[{"stat":"Organizations with formal data governance programs achieve 3.5x faster time-to-value for analytics projects","source":"Gartner, 2024"},{"stat":"82% of manufacturers plan to adopt a data mesh or data fabric architecture within 3 years","source":"Dresner Advisory, 2024"},{"stat":"The cost of poor data quality is estimated at 15-25% of revenue for the average enterprise","source":"MIT Sloan / Gartner, 2024"}]',
  '["Barco","Melexis","Bekaert","Niko","Atlas Copco"]',
  '["How many data sources does your organization currently integrate — and how many are still manual extracts?","Who owns data quality in your organization — is it IT, business, or undefined?","What''s the average lead time from ''I need this data'' to ''I can use this data'' for a new analytics project?"]'
);

-- ─── Value of Data × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('value-of-data', 'operations-leader',
  '{"headline":"Shopfloor data exists everywhere but informs nothing","description":"Machines generate data. Quality systems capture inspections. MES tracks execution. But none of it connects into a single operational picture. Supervisors still walk the floor to understand what''s happening, and root cause analysis takes days instead of minutes.","dataPoint":"Manufacturers with connected shopfloor analytics resolve quality issues 6x faster than those relying on manual analysis — LNS Research, 2024"}',
  '[{"headline":"Operational intelligence is the new lean","detail":"The next wave of continuous improvement isn''t more kaizen workshops — it''s AI-powered anomaly detection that spots drift before it becomes scrap, and automated root cause analysis that finds patterns humans can''t see."},{"headline":"Context turns data into decisions","detail":"A temperature reading means nothing without knowing the product, recipe, machine condition, and operator. Contextualised data enables automated alerts that are actionable, not just noisy."},{"headline":"Democratize data on the shopfloor","detail":"Operators and supervisors should see their own performance data in real-time — not wait for a weekly report from a BI team. Self-service analytics at the line level drives ownership."}]',
  '[{"name":"Power BI Embedded Shopfloor","description":"Real-time dashboards on shopfloor screens with drill-down from KPI to machine level.","partner":"Microsoft"},{"name":"SAP Analytics Cloud","description":"Connected planning and analytics combining financial and operational data.","partner":"SAP"},{"name":"Sight Machine","description":"Manufacturing-specific analytics platform with automated root cause analysis and process optimization.","partner":"Sight Machine"},{"name":"delaware Manufacturing Intelligence","description":"Pre-built analytics models for OEE, quality, energy, and supply chain — deployed in weeks.","partner":"delaware"}]',
  '[{"stat":"Real-time analytics reduces scrap rates by 20-30% in discrete manufacturing environments","source":"McKinsey Operations Practice, 2024"},{"stat":"Manufacturers using AI-powered quality analytics achieve 35% faster root cause identification","source":"LNS Research, 2024"},{"stat":"Self-service analytics adoption on the shopfloor increases operator engagement scores by 18%","source":"Deloitte Human Capital, 2024"}]',
  '["Vandewiele","Picanol","Daikin Europe","Ontex","Bekaert"]',
  '["When a quality issue occurs, how long does it take to identify the root cause today?","Do your operators and supervisors have access to real-time production data at the line?","How many different systems does a production manager need to check to get a complete picture of today''s performance?"]'
);

-- ─── Digital Business × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('digital-business', 'c-level',
  '{"headline":"Your revenue model is stuck in the last decade","description":"Competitors are moving to outcome-based pricing, subscription models, and digital services while you''re still selling hardware with annual maintenance contracts. Customer expectations are shifting to self-service, instant configuration, and seamless digital experiences.","dataPoint":"By 2026, 50% of discrete manufacturers will generate at least 20% of revenue from digital services — IDC, 2024"}',
  '[{"headline":"Servitization is the margin play","detail":"Equipment-as-a-Service and outcome-based contracts create recurring revenue, deeper customer lock-in, and margins 2-3x higher than hardware sales. The data from connected products enables this shift."},{"headline":"B2B buyers expect B2C experiences","detail":"Your customers compare your ordering process to Amazon, not to your competitors. If spare parts ordering, configuration, and service requests aren''t self-service and digital, you''re losing loyalty."},{"headline":"CPQ eliminates the quote-to-cash bottleneck","detail":"Configure-Price-Quote tools turn weeks-long quote cycles into minutes, reduce errors by 90%, and enable sales teams to handle 3x more opportunities."}]',
  '[{"name":"SAP Commerce Cloud","description":"B2B e-commerce platform with deep ERP integration for spare parts, configurators, and customer portals.","partner":"SAP"},{"name":"Dynamics 365 Commerce + CPQ","description":"Unified commerce and configure-price-quote for complex manufacturing products.","partner":"Microsoft"},{"name":"Salesforce Manufacturing Cloud","description":"CRM with account-based forecasting, agreements, and partner management for manufacturers.","partner":"Salesforce"},{"name":"delaware Customer Experience Platform","description":"Integrated portal combining e-commerce, service, knowledge base, and IoT dashboards for customers.","partner":"delaware"}]',
  '[{"stat":"Manufacturers with mature digital commerce channels grow revenue 2.5x faster than peers","source":"McKinsey B2B Digital Commerce, 2024"},{"stat":"73% of B2B buyers prefer self-service for reorders — only 15% of manufacturers offer it","source":"Forrester B2B Commerce, 2024"},{"stat":"CPQ implementations reduce quote cycle time by 83% and increase deal sizes by 105% on average","source":"Salesforce CPQ Benchmark, 2024"}]',
  '["Atlas Copco","TVH","Reynaers Aluminium","Niko","Daikin Europe"]',
  '["What percentage of your revenue today comes from digital services vs. pure hardware sales?","How long does it take from customer inquiry to delivered quote — hours, days, or weeks?","Have your customers asked for self-service portals or digital ordering capabilities?"]'
);

-- ─── Digital Business × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('digital-business', 'it-decision-maker',
  '{"headline":"Customer-facing digital channels are disconnected from back-end reality","description":"Your website shows products that aren''t in stock. Your portal doesn''t reflect real order status. Your CPQ tool doesn''t pull from the latest pricing. The integration gap between front-end digital experience and back-end ERP reality creates a terrible customer experience and manual workarounds.","dataPoint":"Only 22% of manufacturers have real-time integration between their e-commerce platform and ERP — Gartner, 2024"}',
  '[{"headline":"Headless commerce enables omnichannel","detail":"A headless commerce architecture with API-first design lets you serve web portals, mobile apps, and partner integrations from one back-end. Build once, deploy everywhere."},{"headline":"Real-time integration is non-negotiable","detail":"Stock levels, pricing, lead times, and order status must be real-time. Batch updates create a customer experience gap that erodes trust and creates support tickets."},{"headline":"PIM/DAM is the unsung hero","detail":"Product Information Management and Digital Asset Management are the foundation for any digital commerce initiative. Without clean, rich product data, every channel suffers."}]',
  '[{"name":"SAP Commerce + BTP","description":"Headless commerce platform with real-time ERP integration via SAP BTP integration suite.","partner":"SAP"},{"name":"Sitecore + D365 Integration","description":"Digital experience platform with deep CRM and ERP connectivity for personalized B2B experiences.","partner":"Microsoft / Sitecore"},{"name":"Contentserv PIM","description":"Product information management platform tailored for manufacturers with complex product catalogs.","partner":"Contentserv"},{"name":"delaware Commerce Accelerator","description":"Pre-built B2B commerce solution with ERP connectors, CPQ integration, and customer portal templates.","partner":"delaware"}]',
  '[{"stat":"Headless commerce adoption in B2B manufacturing grew 340% between 2022 and 2024","source":"Forrester, 2024"},{"stat":"Manufacturers with real-time ERP-commerce integration reduce order errors by 67%","source":"Aberdeen, 2024"},{"stat":"Poor product data costs manufacturers an average of $3.1M annually in returns, support, and lost sales","source":"Gartner, 2024"}]',
  '["TVH","Reynaers Aluminium","Atlas Copco","Niko","Etex Group"]',
  '["How integrated is your current e-commerce or portal with your ERP — real-time, batch, or manual?","Do you have a single source of truth for product information that feeds all digital channels?","What''s the biggest friction point your customers experience when ordering or getting service online?"]'
);

-- ─── Digital Business × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('digital-business', 'operations-leader',
  '{"headline":"Customer promises and production reality don''t align","description":"Sales promises delivery dates without checking capacity. Customer portals show estimated lead times that bear no relation to actual shopfloor load. Returns and warranty claims are processed manually. The disconnect between customer-facing promises and operational capability destroys trust and efficiency.","dataPoint":"35% of customer complaints in discrete manufacturing stem from delivery date inaccuracy — APICS, 2024"}',
  '[{"headline":"Available-to-Promise needs real-time shopfloor data","detail":"Accurate delivery promises require integrating real-time production capacity, material availability, and current WIP — not static lead times maintained in a spreadsheet."},{"headline":"Aftermarket operations are a profit center, not a cost center","detail":"Spare parts, field service, and warranty management can generate 3-5x the margin of original equipment sales. But only if the operations behind them are digitized and efficient."},{"headline":"Customer feedback loops improve product quality","detail":"Digital channels can capture structured feedback, warranty data, and field failure information that flows directly back to engineering and quality — closing the loop between customer and factory."}]',
  '[{"name":"SAP IBP for Response and Supply","description":"Real-time available-to-promise and capable-to-promise integrated with production planning.","partner":"SAP"},{"name":"D365 Field Service","description":"Connected field service management with IoT integration, scheduling optimization, and mobile execution.","partner":"Microsoft"},{"name":"SAP Service Cloud","description":"Integrated service management with warranty tracking, spare parts management, and knowledge base.","partner":"SAP"},{"name":"delaware Aftermarket Solution","description":"End-to-end aftermarket operations platform connecting spare parts, service, and warranty with ERP.","partner":"delaware"}]',
  '[{"stat":"Manufacturers with integrated ATP reduce delivery date deviations by 45%","source":"Gartner Supply Chain, 2024"},{"stat":"Aftermarket services in discrete manufacturing typically carry 40-60% gross margins vs. 20-30% for new equipment","source":"McKinsey, 2024"},{"stat":"Digital field service reduces mean-time-to-repair by 25% and first-time fix rates improve by 20%","source":"Aberdeen, 2024"}]',
  '["Atlas Copco","TVH","Daikin Europe","Picanol","Vandewiele"]',
  '["How accurate are the delivery dates your sales team promises to customers — and how do you know?","What percentage of your revenue and margin comes from aftermarket services vs. new equipment?","How does customer warranty and complaint data make it back to your engineering and quality teams?"]'
);

-- ─── Frontline Workers × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('frontline-workers', 'c-level',
  '{"headline":"Your most experienced workers are walking out the door","description":"The manufacturing skills gap is accelerating. Experienced operators, technicians, and engineers are retiring faster than you can replace them, taking decades of institutional knowledge with them. Meanwhile, the next generation expects digital tools, not paper binders.","dataPoint":"2.1 million manufacturing jobs will go unfilled by 2030 due to the skills gap — Deloitte & Manufacturing Institute, 2024"}',
  '[{"headline":"Digital tools are a recruitment advantage","detail":"Gen Z and millennial workers choose employers based on technology. Modern digital work instructions, AR/VR training, and AI copilots signal an innovative workplace that attracts talent."},{"headline":"Knowledge capture is a strategic imperative","detail":"Every retiring expert takes 30+ years of problem-solving intuition. Capturing this as digital work instructions, video guides, and AI-searchable knowledge bases is not optional — it''s urgent."},{"headline":"Productivity per worker must increase","detail":"If you can''t hire enough people, each person needs to be more productive. AI copilots, smart work instructions, and cobots augment human capability without requiring years of training."}]',
  '[{"name":"Microsoft Copilot for Manufacturing","description":"AI assistant that helps workers access procedures, troubleshoot issues, and complete tasks using natural language.","partner":"Microsoft"},{"name":"PTC Vuforia Expert Capture","description":"AR-based knowledge capture and delivery — experienced workers record procedures that new hires follow step-by-step.","partner":"PTC"},{"name":"SAP Enable Now","description":"Digital adoption platform with in-application guidance, e-learning, and performance support.","partner":"SAP"},{"name":"delaware Connected Worker Platform","description":"Integrated solution combining digital work instructions, skills management, and performance tracking.","partner":"delaware"}]',
  '[{"stat":"Manufacturers using digital work instructions reduce training time by 50% and errors by 90%","source":"LNS Research, 2024"},{"stat":"83% of manufacturers cite workforce challenges as their top operational risk","source":"Deloitte & Manufacturing Institute, 2024"},{"stat":"Companies investing in frontline worker technology see 32% lower turnover rates","source":"Microsoft Work Trend Index, 2024"}]',
  '["Atlas Copco","Daikin Europe","Vandewiele","CNH Industrial","Ontex"]',
  '["How many of your most experienced operators and technicians will retire in the next 5 years?","How long does it take to bring a new shopfloor worker to full productivity today?","Have you quantified the cost of the knowledge that leaves when experienced workers retire?"]'
);

-- ─── Frontline Workers × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('frontline-workers', 'it-decision-maker',
  '{"headline":"Frontline workers are the last mile of digital transformation","description":"You''ve invested in ERP, MES, and analytics — but the people on the shopfloor still work with paper instructions, verbal handoffs, and tribal knowledge. The digital thread breaks at the point where value is actually created.","dataPoint":"Only 1% of enterprise software investment goes to frontline worker tools — despite frontline workers being 80% of the global workforce — Microsoft, 2024"}',
  '[{"headline":"Wearables and mobile devices are production tools","detail":"Ruggedized tablets, smart glasses, and wearables aren''t gadgets — they''re the interface between digital systems and physical work. The UX must be designed for gloves, noise, and movement."},{"headline":"AI at the edge enables real-time assistance","detail":"On-device AI models can provide real-time quality checks, step-by-step guidance, and safety alerts without requiring cloud connectivity — critical for environments with intermittent network."},{"headline":"Low-code platforms democratize app creation","detail":"Power Apps and similar tools let operations teams build their own frontline apps — shift handover, checklists, incident reporting — without waiting in the IT backlog."}]',
  '[{"name":"Microsoft Teams + Viva + Power Apps","description":"Frontline worker platform combining communication, learning, and custom apps for shopfloor scenarios.","partner":"Microsoft"},{"name":"PTC Vuforia + HoloLens","description":"Augmented reality for assembly guidance, remote expert assistance, and quality inspection.","partner":"PTC / Microsoft"},{"name":"SAP Digital Manufacturing (Work Instructions)","description":"Digital work instructions with 3D visualization, integrated quality checks, and automatic time capture.","partner":"SAP"},{"name":"RealWear Navigator","description":"Hands-free head-mounted device for industrial AR applications — voice-controlled, intrinsically safe.","partner":"RealWear"}]',
  '[{"stat":"AR-guided assembly reduces errors by 94% and time-to-competence by 40%","source":"Harvard Business Review / PTC, 2024"},{"stat":"65% of manufacturers plan to deploy AI-powered assistants for frontline workers by 2026","source":"IDC Manufacturing, 2024"},{"stat":"Low-code frontline apps reduce IT backlog by 35% while improving shopfloor data capture by 60%","source":"Forrester, 2024"}]',
  '["Barco","Daikin Europe","Atlas Copco","Melexis","CNH Industrial"]',
  '["What percentage of your shopfloor processes still rely on paper-based instructions or documentation?","Have you piloted AR or AI-assisted tools for assembly, maintenance, or quality inspection?","How do frontline workers currently access the information they need — and how long does it take to find it?"]'
);

-- ─── Frontline Workers × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('frontline-workers', 'operations-leader',
  '{"headline":"New hires take months to become productive — you don''t have months","description":"Training new operators used to mean shadowing an expert for weeks. But experts are scarce, production pressure is constant, and the skills required are increasingly complex. The result: longer ramp-up times, more quality issues from inexperienced workers, and constant firefighting.","dataPoint":"Average time-to-competence for a new manufacturing operator has increased from 6 weeks to 14 weeks since 2019 — Manufacturing Institute, 2024"}',
  '[{"headline":"Digital work instructions standardize best practices","detail":"Interactive, visual work instructions ensure every operator follows the best-known method — regardless of experience level. This reduces variation, improves quality, and makes tribal knowledge explicit."},{"headline":"AI copilots augment, not replace","detail":"An AI assistant that can answer ''how do I set up machine X for product Y?'' in natural language is like giving every worker access to your best expert 24/7. It augments capability without threatening jobs."},{"headline":"Skills matrices meet digital learning","detail":"Connecting your skills management with digital learning paths and on-the-job validation creates a continuous improvement loop for workforce capability — measurable and auditable."}]',
  '[{"name":"PTC Vuforia Step Check","description":"AI-powered visual inspection that guides operators and verifies assembly steps in real-time.","partner":"PTC"},{"name":"Microsoft Copilot for Dynamics 365","description":"AI assistant providing natural language access to procedures, troubleshooting, and historical data.","partner":"Microsoft"},{"name":"Tulip Frontline Operations","description":"No-code platform for building digital SOPs, quality checks, and machine monitoring apps.","partner":"Tulip"},{"name":"delaware Skills & Training Suite","description":"Integrated skills matrix, learning management, and on-the-job validation for manufacturing teams.","partner":"delaware"}]',
  '[{"stat":"Digital work instructions reduce training time by 50% and improve first-pass quality by 30%","source":"LNS Research, 2024"},{"stat":"Manufacturing workers using AI copilots complete complex tasks 40% faster with 25% fewer errors","source":"Microsoft Research, 2024"},{"stat":"68% of frontline manufacturing workers say better digital tools would make them more likely to stay","source":"Deloitte Connected Worker Survey, 2024"}]',
  '["Vandewiele","Picanol","Ontex","Daikin Europe","Atlas Copco"]',
  '["How long does it take for a new operator to work independently on your most complex products?","How do you currently capture and transfer knowledge from your most experienced workers?","If you could give every operator an AI assistant that knows all your procedures — would that change your staffing equation?"]'
);

-- ─── Resilience, Compliance & Control × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('resilience-compliance', 'c-level',
  '{"headline":"Regulatory pressure, supply chain shocks, and cyber threats are converging","description":"CSRD, CBAM, NIS2, supply chain disruptions, and escalating cyber attacks are hitting simultaneously. Each alone is manageable; together they demand a level of visibility, control, and agility that most manufacturers don''t have.","dataPoint":"76% of manufacturing CEOs expect regulatory compliance costs to increase by 20%+ over the next 3 years — PwC, 2024"}',
  '[{"headline":"Compliance is a competitive advantage, not just a cost","detail":"Companies that embed ESG, cybersecurity, and supply chain resilience into their operating model win customer trust, access better financing, and attract top talent. It''s a differentiator, not overhead."},{"headline":"Supply chain visibility requires end-to-end digitization","detail":"You can''t manage what you can''t see. Multi-tier supply chain visibility — from raw materials to final delivery — requires digital platforms, not quarterly supplier surveys."},{"headline":"Cyber risk is existential for manufacturing","detail":"A ransomware attack doesn''t just take down IT — it stops production lines, corrupts quality data, and can trigger regulatory breaches. OT security is as important as IT security."}]',
  '[{"name":"SAP Sustainability Control Tower","description":"End-to-end ESG management with carbon accounting, CSRD reporting, and circular economy tracking.","partner":"SAP"},{"name":"Microsoft Defender for IoT","description":"OT security monitoring for industrial environments — detect threats to SCADA, PLC, and IoT systems.","partner":"Microsoft"},{"name":"SAP Ariba + Business Network","description":"Supply chain collaboration platform with supplier risk management and multi-tier visibility.","partner":"SAP"},{"name":"delaware Compliance Framework","description":"Integrated approach to NIS2, CSRD, CBAM compliance with gap assessment, roadmap, and implementation.","partner":"delaware"}]',
  '[{"stat":"Manufacturing is the #1 target industry for cyberattacks for the third consecutive year","source":"IBM X-Force Threat Intelligence, 2024"},{"stat":"CSRD will require 50,000+ European companies to report detailed sustainability data starting 2025-2026","source":"European Commission, 2024"},{"stat":"Supply chain disruptions cost the average manufacturer $184M annually in lost revenue and increased costs","source":"Interos, 2024"}]',
  '["Bekaert","Etex Group","Barco","Reynaers Aluminium","CNH Industrial"]',
  '["How prepared is your organization for CSRD reporting — do you have the data, processes, and systems in place?","When was the last time a supply chain disruption materially impacted your revenue or customer commitments?","Has your board discussed OT cybersecurity as a specific risk category — separate from general IT security?"]'
);

-- ─── Resilience, Compliance & Control × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('resilience-compliance', 'it-decision-maker',
  '{"headline":"You''re responsible for securing a converging IT/OT landscape you don''t fully control","description":"NIS2 mandates cybersecurity standards. CSRD demands data you''ve never collected. Legacy OT equipment has no security by design. And every IoT sensor you add expands the attack surface. The CISO role in manufacturing is becoming the hardest job in the company.","dataPoint":"56% of manufacturers have experienced a cyber incident affecting OT systems in the past year — Fortinet, 2024"}',
  '[{"headline":"Zero-trust architecture for the factory floor","detail":"Network segmentation, identity management, and continuous monitoring for OT environments — the same zero-trust principles proven in IT, adapted for industrial protocols and real-time requirements."},{"headline":"NIS2 compliance requires IT/OT governance alignment","detail":"NIS2 doesn''t distinguish between IT and OT. Incident reporting, risk management, and supply chain security obligations apply to your entire digital footprint — including the shopfloor."},{"headline":"Sustainability data architecture is an IT project","detail":"CSRD requires auditable data flows from energy meters, production systems, supply chain platforms, and HR systems. This is fundamentally a data integration and governance challenge."}]',
  '[{"name":"Microsoft Sentinel + Defender for IoT","description":"SIEM and XDR platform with specific OT threat detection for manufacturing environments.","partner":"Microsoft"},{"name":"SAP GRC (Governance, Risk, Compliance)","description":"Integrated risk management and compliance platform with manufacturing-specific controls.","partner":"SAP"},{"name":"Claroty / Nozomi Networks","description":"Industrial cybersecurity platforms for OT asset discovery, threat detection, and network segmentation.","partner":"Claroty / Nozomi"},{"name":"delaware NIS2 Readiness Assessment","description":"Gap analysis, roadmap, and implementation support for NIS2 compliance across IT and OT.","partner":"delaware"}]',
  '[{"stat":"NIS2 mandates 24-hour incident notification and personal liability for management — effective October 2024","source":"European Commission, 2024"},{"stat":"The average cost of a cyber breach in manufacturing is $4.73M — 12% higher than the cross-industry average","source":"IBM Cost of a Data Breach, 2024"},{"stat":"Only 21% of manufacturers have a unified security operations center covering both IT and OT environments","source":"SANS ICS/OT Survey, 2024"}]',
  '["Barco","Bekaert","Melexis","Niko","Etex Group"]',
  '["Do you have complete visibility into all OT assets connected to your network — including legacy equipment?","How would your organization handle a NIS2-mandated 24-hour incident notification today?","Is your sustainability data architecture ready for external audit — or is it still a spreadsheet exercise?"]'
);

-- ─── Resilience, Compliance & Control × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('resilience-compliance', 'operations-leader',
  '{"headline":"Compliance is consuming operational bandwidth that should go to production","description":"Quality audits, environmental reporting, safety documentation, supplier certifications — the compliance burden keeps growing while your team size doesn''t. Manual compliance processes steal time from value-creating activities and introduce error risk.","dataPoint":"Manufacturing compliance teams spend 52% of their time on manual data collection and documentation — Make UK, 2024"}',
  '[{"headline":"Automated compliance frees operational capacity","detail":"When quality, safety, and environmental data is captured automatically as part of production, compliance becomes a byproduct of operations — not a separate workstream."},{"headline":"Supply chain resilience starts with visibility","detail":"You can''t mitigate supplier risks you can''t see. Real-time supply chain monitoring with alternative sourcing scenarios lets you respond to disruptions in hours, not weeks."},{"headline":"Energy management is cost management","detail":"With energy costs at all-time highs, real-time energy monitoring and optimization at the machine level directly impacts margin. It also generates the data you need for CSRD reporting."}]',
  '[{"name":"SAP EHS (Environment, Health & Safety)","description":"Integrated compliance management for environmental reporting, incident tracking, and safety management.","partner":"SAP"},{"name":"Microsoft Sustainability Manager","description":"Carbon accounting and ESG reporting with automated data collection from across the enterprise.","partner":"Microsoft"},{"name":"SAP IBP for Supply Chain","description":"Scenario planning and risk simulation for supply chain resilience with multi-tier visibility.","partner":"SAP"},{"name":"delaware Energy & Sustainability Platform","description":"Real-time energy monitoring, carbon footprint tracking, and CSRD reporting integrated with production data.","partner":"delaware"}]',
  '[{"stat":"Automated compliance workflows reduce documentation effort by 60% and audit findings by 40%","source":"Make UK Digital Manufacturing, 2024"},{"stat":"Manufacturers with real-time energy monitoring reduce energy costs by 15-25% within the first year","source":"IEA Industrial Energy, 2024"},{"stat":"Companies with mature supply chain risk management recover from disruptions 2x faster than peers","source":"Gartner Supply Chain, 2024"}]',
  '["Etex Group","Bekaert","Ontex","Reynaers Aluminium","Daikin Europe"]',
  '["How much of your team''s time is spent on compliance documentation vs. production improvement?","Do you have real-time visibility into energy consumption at the machine or line level?","If your top 3 suppliers went offline tomorrow, how quickly could you activate alternatives?"]'
);

-- ─── Talent & Knowledge × C-Level ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('talent-knowledge', 'c-level',
  '{"headline":"Your most valuable asset is undocumented and retiring","description":"Decades of engineering expertise, process knowledge, and customer insights live in people''s heads, personal files, and informal networks. When they leave — and they''re leaving at record rates — that knowledge is gone forever.","dataPoint":"40% of manufacturing knowledge is tacit and undocumented — estimated value at risk: $1.5T globally — Accenture, 2024"}',
  '[{"headline":"Knowledge management is risk management","detail":"Every key person departure is a potential capability gap. Systematic knowledge capture — from design rationale to process know-how — converts personal assets into organizational assets."},{"headline":"PLM is the backbone of engineering knowledge","detail":"Product Lifecycle Management isn''t just document storage — it''s the digital thread that connects design intent, manufacturing constraints, field performance, and continuous improvement across the entire product lifecycle."},{"headline":"AI transforms knowledge from static to dynamic","detail":"Generative AI can make 30 years of engineering documents, service reports, and quality records searchable and actionable. Instead of searching, workers can ask — and get contextual, accurate answers."}]',
  '[{"name":"Siemens Teamcenter / PTC Windchill","description":"Enterprise PLM platforms for engineering data management, BOM governance, and change management.","partner":"Siemens / PTC"},{"name":"Microsoft Copilot + SharePoint Premium","description":"AI-powered knowledge search and synthesis across all enterprise documents and systems.","partner":"Microsoft"},{"name":"SAP Enterprise Product Development","description":"Integrated PLM-to-ERP digital thread connecting engineering, manufacturing, and service data.","partner":"SAP"},{"name":"delaware Knowledge Intelligence","description":"AI-powered knowledge management combining document AI, expert networks, and contextual search.","partner":"delaware"}]',
  '[{"stat":"Organizations with mature knowledge management practices achieve 35% faster time-to-market","source":"APQC, 2024"},{"stat":"The average manufacturer loses $4.5M annually due to knowledge gaps from employee turnover","source":"Deloitte Manufacturing Workforce, 2024"},{"stat":"AI-powered knowledge search reduces time-to-answer by 73% compared to traditional document search","source":"Microsoft Enterprise Data, 2024"}]',
  '["Atlas Copco","Barco","CNH Industrial","Vandewiele","Bekaert"]',
  '["If your top 5 engineers or process experts left tomorrow, what knowledge would you lose?","How connected is your product design data to manufacturing execution and field service feedback?","Have you explored AI-powered tools that can make your institutional knowledge searchable and accessible?"]'
);

-- ─── Talent & Knowledge × IT Decision Maker ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('talent-knowledge', 'it-decision-maker',
  '{"headline":"Knowledge is trapped in 50 different systems and nobody can find anything","description":"Engineering data in PLM. Procedures in SharePoint. Quality records in QMS. Training materials in LMS. Service history in CRM. The knowledge exists, but it''s fragmented across systems with different taxonomies, access controls, and search capabilities. Finding the right information takes longer than applying it.","dataPoint":"Knowledge workers spend 1.8 hours per day — 9.3 hours per week — searching for and gathering information — McKinsey, 2024"}',
  '[{"headline":"A knowledge graph connects the dots","detail":"Instead of centralizing all knowledge in one system, build a semantic layer that connects knowledge across systems. A manufacturing knowledge graph links products, processes, people, and problems."},{"headline":"PLM modernization enables the digital thread","detail":"Legacy PLM systems are file vaults. Modern PLM platforms (Teamcenter, Windchill, 3DExperience) enable model-based definitions, configuration management, and full lifecycle traceability."},{"headline":"GenAI is the knowledge interface of the future","detail":"Retrieval-Augmented Generation (RAG) on your internal knowledge base gives every worker an AI expert that knows your products, processes, and history. The technology is ready — the data preparation is the work."}]',
  '[{"name":"Microsoft Copilot Studio","description":"Build custom AI assistants grounded in your organization''s data across M365, SAP, and custom sources.","partner":"Microsoft"},{"name":"PTC Windchill + Creo","description":"Model-based PLM with digital thread connectivity from CAD to BOM to shopfloor.","partner":"PTC"},{"name":"Azure AI Search + OpenAI","description":"Enterprise RAG platform for building intelligent search and Q&A over internal knowledge repositories.","partner":"Microsoft"},{"name":"delaware Knowledge Graph Platform","description":"Manufacturing-specific knowledge graph connecting PLM, ERP, QMS, and service data in a unified semantic model.","partner":"delaware"}]',
  '[{"stat":"Enterprise knowledge graph adoption in manufacturing grew 200% in 2023-2024","source":"Gartner Emerging Tech, 2024"},{"stat":"RAG-based enterprise search achieves 92% accuracy vs. 64% for traditional keyword search on technical content","source":"Microsoft Research, 2024"},{"stat":"PLM modernization projects deliver 25% reduction in engineering change cycle time","source":"CIMdata, 2024"}]',
  '["Barco","Atlas Copco","Bekaert","Melexis","CNH Industrial"]',
  '["How many different systems does an engineer need to search to answer a product-related question today?","What''s the status of your PLM platform — is it a modern digital thread or a legacy document vault?","Have you piloted any GenAI or RAG-based tools for internal knowledge search?"]'
);

-- ─── Talent & Knowledge × Operations Leader ───
INSERT INTO storyline_content (storyline_id, persona_id, pain_point, strategic_talking_points, tactical_solutions, market_insights, reference_customers, conversation_starters) VALUES
('talent-knowledge', 'operations-leader',
  '{"headline":"Tribal knowledge runs your factory — and it''s a single point of failure","description":"The operator who knows exactly how to set up Machine 7 for Product X. The quality inspector who can spot a defect by sound. The maintenance tech who remembers every workaround. This knowledge is priceless — and it''s completely undocumented.","dataPoint":"72% of manufacturing process knowledge is held by less than 15% of the workforce — MESA International, 2024"}',
  '[{"headline":"Digital SOPs are living knowledge","detail":"Static PDF work instructions are always out of date. Digital SOPs that connect to the latest engineering changes, include video from experts, and track operator feedback create a living knowledge system."},{"headline":"Cross-training becomes scalable with digital tools","detail":"When expert knowledge is captured digitally, you can train 10 people simultaneously instead of one-on-one shadowing. Skills matrices combined with digital learning paths make workforce flexibility systematic."},{"headline":"Every quality escape is a knowledge gap","detail":"Root cause analysis often reveals that knowledge existed but wasn''t accessible at the point of need. Connecting quality events to knowledge management closes this loop and prevents repeat issues."}]',
  '[{"name":"PTC Vuforia Expert Capture","description":"Record expert procedures as AR-guided instructions that anyone can follow step-by-step.","partner":"PTC"},{"name":"Tulip Knowledge Base","description":"Frontline-accessible knowledge management with multimedia content, integrated into digital workflows.","partner":"Tulip"},{"name":"Microsoft Viva Learning + Engage","description":"Social learning and knowledge sharing platform with AI-curated content and expert identification.","partner":"Microsoft"},{"name":"delaware Digital Knowledge Transfer","description":"Structured methodology and tools for capturing, digitizing, and deploying expert manufacturing knowledge.","partner":"delaware"}]',
  '[{"stat":"Digital SOPs reduce procedural errors by 90% and increase first-pass yield by 25%","source":"LNS Research, 2024"},{"stat":"AR-guided knowledge transfer reduces expert-to-novice skill transfer time from 12 weeks to 4 weeks","source":"PTC Customer Data, 2024"},{"stat":"58% of quality escapes in manufacturing are traceable to knowledge accessibility gaps — not knowledge absence","source":"ASQ Manufacturing Division, 2024"}]',
  '["Vandewiele","Picanol","Daikin Europe","Ontex","Atlas Copco"]',
  '["If you had to ramp up a new production line with entirely new operators, how long would it take?","How do you currently capture what your best operators know — and how do you share it?","When a quality issue occurs, how quickly can an operator access the relevant procedure or troubleshooting guide?"]'
);
